### PR TITLE
Starting a list of integrations

### PR DESCRIPTION
**Pull request by marclaporte**
Let's work towards many projects using!

### CODE REVIEW

**Comment by ogmueller** [comment]
merging tikiwiki pull request

**Comment by kroky** [comment]
@ogmueller Thanks for the excellent implementation! We have a bit of a trouble with symfony/console dependency and package versions - the only 2 versions we can use in Tiki Wiki CMS Groupware integration are 1.0.x-dev which depends on symfony/console 2.x and dev-master which depends on symfony/console 5.x. Our currently big set of package dependencies is stuck with symfony/console 3.x. Is there any way we have a version of this library that is compatible with 3.x without making a fork?

**Comment by ogmueller** [comment]
Can you check commit d9ca4fa? Does that help?

**Comment by kroky** [comment]
That would definitely help. Thanks for the quick addition!

**Pull request merged**
